import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { mapboxToken } from '../mapboxToken'

var mapboxgl = require('mapbox-gl/dist/mapbox-gl.js');


const Home: NextPage = () => {

  const [pageIsMounted, setPageIsMounted] = useState(false)
  const [Map, setMap] = useState();

  mapboxgl.accessToken = mapboxToken;

  useEffect(() => {
    setPageIsMounted(true)

    let map = new mapboxgl.Map({
      container: "my-map",
      style: "mapbox://styles/mapbox/streets-v11",
      center: [7.751154323216781,48.58156854870154],
      zoom: 11,
      pitch: 15,
      // maxBounds: [
      //   [-77.875588, 38.50705], // Southwest coordinates
      //   [-76.15381, 39.548764], // Northeast coordinates
      // ],
    });

    map.addControl(
      new mapboxgl.GeolocateControl({
        positionOptions: {
          enableHighAccuracy: true,
        },
        trackUserLocation: true,
      })
    );

    setMap(map);

    map.on('click', (event: any) => {
      const clickedPoint = [event.lngLat.lng, event.lngLat.lat];
      console.log(JSON.stringify(clickedPoint));
      new mapboxgl.Marker({
        color: "#9acdad",
        draggable: true
      }).setLngLat(clickedPoint).addTo(map)
    });


  }, [])


  // let marker = new mapboxgl.Marker({
  //   color: "#6a0dad",
  //   draggable: true
  // })
  //   .setLngLat([7.79, 48.59])
  //   .addTo(Map);

  return (
    <div className={styles.container}>
      <Head>
        <title>Mapbox Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
      </Head>
      <div style={{ display: "flex" }}>
        <div id="my-map" style={{ height: 450, width: '50%' }} />
        <div style={{ display: "flex", flexDirection: "column", justifyContent: "space-around", marginLeft: "2rem" }} className="btn-group">
          <button onClick={() => new mapboxgl.Marker({
            color: "#6a0dad",
            draggable: true
          }).setLngLat([7.800972268987692,48.60929041022874]).addTo(Map)}>Ajouter une étape à la Robertsau</button>
          <button onClick={() => new mapboxgl.Marker({
            color: "#1a0dad",
            draggable: true
          }).setLngLat([7.776089887433045,48.58998127994283]).addTo(Map)}>Ajouter un point d'intérêt à l'Orangerie</button>
          {/* <button onClick={() => new mapboxgl.Marker({
            color: "#6a0dad",
            draggable: true
          }).setLngLat([7.79, 48.59]).addTo(Map)}>Button</button> */}

        </div>
      </div>

    </div>
  )
}

export default Home
